services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    env_file:
      - ./apps/auth/.env

  jobs:
    build:
      context: .
      dockerfile: ./apps/jobs/Dockerfile
      target: development
    command: npm run start:dev jobs
    ports:
      - '8081:8081'
    volumes:
      - .:/app
    env_file:
      - ./apps/jobs/.env

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    volumes:
      - .:/app
    env_file:
      - ./apps/payments/.env

  chat:
    build:
      context: .
      dockerfile: ./apps/chat/Dockerfile
      target: development
    command: npm run start:dev chat
    ports:
      - '8083:8083'
    volumes:
      - .:/app
    env_file:
      - ./apps/chat/.env

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications
    ports:
      - '8082:8082'
    volumes:
      - .:/app
    env_file:
      - ./apps/notifications/.env

  mongo-server:
    image: mongo
    logging:
      driver: none

  rmq-server:
    image: rabbitmq
    logging:
      driver: none

  redis-server:
    image: redis
    logging:
      driver: none
